### ISSUE TITLE
<code>の説明表示を希望します

### ISSUE THREAD

**Issue by tukiyo** [tatesuke/KanTanMarkdown#134]
独自タグでそれっぽくしてみました。よかったら取り込んでください。

``` css
/* START_CODE_TITLE */
f {
    display:inline;
    background-color: rgba(0,0,0,0.07); 
    color: #555;
    font-size: 0.8em;
    font-weight: 400;
    padding: .25em .5em;
}
f + pre {
    margin-top: 0;
}
/* END_CODE_TITLE */
```

![test](https://cloud.githubusercontent.com/assets/1517645/16673448/3f5aed12-44e9-11e6-8501-89ab063371d6.png)

`f`は極力短い文字かつ左手を動かさずに入力できる文字として選びました。
